package com.ssm.test.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.ssm.test.entity.User;
@Repository("userDao")
public interface UserDao {
    /**	
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ssm_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ssm_user
     *
     * @mbggenerated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ssm_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ssm_user
     *
     * @mbggenerated
     */
    User selectByPrimaryKey(Integer userid);

    /**
     * 用于查询所有user
     */
    List<User>selectAll();
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ssm_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_ssm_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(User record);
}